### PR TITLE
Add Romanian language to list of languages using street prefix

### PR DESCRIPTION
**Pull request by taygun**
In Romania street types are used as prefix https://www.openstreetmap.org/#map=17/44.43396/26.01652

### CODE REVIEW

**Comment by orangejulius** [comment]
Looks like a good change. @missinglink should we bring in the rest of the values from https://github.com/pelias/api/blob/master/middleware/localNamingConventions.js?

**Comment by missinglink** [comment]
Looks great thanks @taygun

It would be super helpful if we had a few example addresses from Romania in our test suite.

Here's an example of some recent additions for Czech Republic:
https://github.com/pelias/parser/blob/master/test/address.cze.test.js

**Comment by missinglink** [comment]
@orangejulius that functionality is actually different although the list might have some common country codes.

This issue is for `Foo Ave` vs `Ave Foo` whereas the Pelias country code list you linked is for `1 Foo Ave` vs. `Foo Ave 1`.

**Comment by taygun** [comment]
> Looks great thanks @taygun
> 
> It would be super helpful if we had a few example addresses from Romania in our test suite.
> 
> Here's an example of some recent additions for Czech Republic:
> https://github.com/pelias/parser/blob/master/test/address.cze.test.js

Great @missinglink, I will add a few examples from Romania today.

**Comment by bboure** [comment]
I wonder if this list should probably contain all (or most of) the latin based languages. Italian (it) should be added for sure. Also `gl` (Galician), too

**Comment by missinglink** [comment]
Yeah definitely, that would be great to have.

I think it would be better to do that in another PR so this one can stay focussed on Romania and we can get it merged today.

I know it's a fair bit of work but having at least one or two example addresses for each of those countries is super useful for future reference.

**Comment by missinglink** [comment]
I'm also confusing myself here, these are language codes not country codes, but it makes sense to include tests from a country which uses each language.

**Comment by missinglink** [comment]
fantastic thanks!

**Comment by missinglink** [comment]
this change has been published as `npm` version `1.54.0`

**Comment by taygun** [comment]
> fantastic thanks!

Thank you also for an amazing project!

**Pull request merged**
