### PR TITLE
Add Classifier and Classification for road names

### LINKED ISSUE #36: german addresses parsed as street
there is a minor regression where complete german addresses can be parsed as a street, such as the example `foostraße 10` below:

Screenshot 2019-06-05 at 14 01 47

It's not detected in the tests because it's not the top result but we should still remove these matches because they don't seem to make sense logically?

### LINKED ISSUE #61: can we avoid numeric street suffixes or score them lower?
The following example is a partially complete 'autocomplete-style' query where the `street` and `housenumber` have been entered but the `postcode` is only partially complete.

In this case, the correct result would be `street:Eberswalder Straße` `housenumber:100` but for some reason, the street name is being detected as `Eberswalder Straße 100:

```
node bin/cli.js 'Eberswalder Straße 100 104'

================================================================
TOKENIZATION (1ms)
----------------------------------------------------------------
INPUT                           ➜  Eberswalder Straße 100 104
SECTIONS                        ➜   Eberswalder Straße 100 104  0:26
S0 TOKENS                       ➜   Eberswalder  0:11   Straße  12:18   100  19:22   104  23:26
S0 PHRASES                      ➜   Eberswalder Straße 100 104  0:26   Eberswalder Straße 100  0:22   Eberswalder Straße  0:18   Eberswalder  0:11   Straße 100 104  12:26   Straße 100  12:22   Straße  12:18   100 104  19:26   100  19:22   104  23:26

================================================================
CLASSIFICATIONS (2ms)
----------------------------------------------------------------
WORDS
----------------------------------------------------------------
Eberswalder                     ➜   alpha  1.00   start_token  1.00
Straße                          ➜   alpha  1.00   street_suffix  1.00
100                             ➜   numeric  1.00   housenumber  1.00
104                             ➜   numeric  1.00   end_token  1.00   housenumber  1.00

----------------------------------------------------------------
PHRASES
----------------------------------------------------------------
Eberswalder Straße              ➜   street  0.82
Eberswalder Straße 100          ➜   street  0.84

================================================================
SOLUTIONS (1ms)
----------------------------------------------------------------
(0.86) ➜ [ { street: 'Eberswalder Straße 100' }, { housenumber: '104' } ]

(0.74) ➜ [ { street: 'Eberswalder Straße' }, { housenumber: '100' } ]
```

### PR DESCRIPTION
**Pull request by Joxit**
Streets ending with numbers are often used in the US for streets that look like road names, such as `State Highway 10`.

This is a specific use case that can't be applied to all streets and cause side effects. That's why I added a specific classifier for this type of streets.

This is the first part of the road-name refactoring. The next part will be the support of alias names (#60).

fixes #61 
fixes #36

### CODE REVIEW

**Comment by missinglink** [comment]
Great idea, I like it.

I'd be a little hesitant to introduce a new label `road_name` when we already have `street`.

For consuming programs such as Pelias API, they will need a list of all possible labels for the concept of a 'way' and then code for them accordingly, if we introduce a new label again (like 'cycleway' for instance), then the API code would need to be updated again.

In some cases it might be better to have a distinction between the different types of 'way', as per osm, but in most cases it's easier for the consumer if they are grouped under a single label, as per libpostal.

Thoughts?

**Comment by missinglink** [comment]
IIRC the labels are only used for display when generating the solution (and not for internal referencing) so we could adopt a convention such as `street:highway` and then allow the consuming program to use only the prefix if desired.

Internally, there is code to ensure that, for instance, no solution contains more than one street name (with the exception of intersections), so this PR might open up a big where an address parse contained both a street and a road?

**Comment by Joxit** [comment]
In this PR `road_name` is a hidden label so Pelias API will see `street` and not `road_name` (internal use only). I realize, it should not be `road_name` but `road_type` :thinking: because this classify `State Highway` and not `State Highway 10`.

But I like your idea to use `street:highway`. This will help the API to know when it will have to change `IA 10` to `State Highway 10` for example. But yes this will be a bit more complicated to do..

Intersections seems to be OK with this PR since they are classified as `street`.

```
node bin/cli.js 'main st & State Highway 10'

================================================================
TOKENIZATION (2ms)
----------------------------------------------------------------
INPUT                           ➜  main st & State Highway 10
SECTIONS                        ➜   main st & State Highway 10  0:26 
S0 TOKENS                       ➜   main  0:4   st  5:7   &  8:9   State  10:15   Highway  16:23   10  24:26 
S0 PHRASES                      ➜   main st & State Highway 10  0:26   main st & State Highway  0:23   main st & State  0:15   main st &  0:9   main st  0:7   main  0:4   st & State Highway 10  5:26   st & State Highway  5:23   st & State  5:15   st &  5:9   st  5:7   & State Highway 10  8:26   & State Highway  8:23   & State  8:15   &  8:9   State Highway 10  10:26   State Highway  10:23   State  10:15   Highway 10  16:26   Highway  16:23   10  24:26 

================================================================
CLASSIFICATIONS (5ms)
----------------------------------------------------------------
WORDS
----------------------------------------------------------------
main                            ➜   alpha  1.00   start_token  1.00  
st                              ➜   alpha  1.00   street_suffix  1.00  
&                               ➜   punctuation  1.00   stop_word  0.20   intersection  1.00  
State                           ➜   alpha  1.00  
Highway                         ➜   alpha  1.00   street_suffix  1.00   road_name  1.00  
10                              ➜   numeric  1.00   end_token  1.00   housenumber  1.00  

----------------------------------------------------------------
PHRASES
----------------------------------------------------------------
&                               ➜   intersection  1.00  
st                              ➜   personal_suffix  1.00   personal_title  1.00   area  1.00   country  0.90  
main                            ➜   surname  1.00  
State                           ➜   street  0.56  
main st                         ➜   street  0.82  
& State                         ➜   street_name  0.50  
Highway 10                      ➜   street  0.84  
st & State                      ➜   street_name  0.50   multistreet  1.00  
State Highway                   ➜   street  0.82  
State Highway 10                ➜   street  0.84  

================================================================
SOLUTIONS (3ms)
----------------------------------------------------------------
(0.79) ➜ [ { street: 'main st' }, { street: 'State Highway 10' } ]

(0.56) ➜ [ { street: 'State Highway' }, { housenumber: '10' } ]
```

**Comment by missinglink** [comment]
Agh that makes sense, I'm already forgetting how it works ;)

**Comment by Joxit** [comment]
:smile: I rename the classifier/classification to RoadType instead of RoadName for this PR ? And we will see for `street:highway` later ?

**Comment by missinglink** [comment]
Sounds good to me 👍

**Comment by Joxit** [comment]
Done, I renamed road_name to road_type and added some tests :smile:

**Pull request merged**
