### PR TITLE
rename "assert" function to be more readable

### PR DESCRIPTION
**Pull request by blackmad**
I was confused when adding tests by the assert function, both because I
am used to "assert" being from a testing library as well as true/false
not being immediately obvious what it did

:wave: I did some awesome work for the Pelias project and would love for everyone to have a look at it and provide feedback.

### CODE REVIEW

**Comment by missinglink** [comment]
ah ok... so I don't want to get into a semantics debate ;)

I named it `assert` and you named it `assertFirstParseMatches` so without another opinion we're at somewhat of an impasse?
Can you suggest a way to resolve this subjectivity objectively?

**Comment by orangejulius** [comment]
I'll break the deadlock :laughing: 

David is right, `assert` is too generic a name and has too specific of a commonly known meaning when it comes to testing.

How about `assertFirstMatch` so it's a little shorter but clearly parser specific?

**Comment by blackmad** [comment]
changed to assertFirstMatch and assertAllMatch

**Comment by Joxit** [comment]
Hi there, please avoid merging branches and prefer rebase + push force

```sh
git fetch upstream master
git rebase upstream/master
git push -f origin rename-assert
```
I know there are more commands, but branches are prettier with that :sweat_smile:

**Comment by missinglink** [comment]
Just getting back to this, sorry for the delay.
Sorry I was in a rush and my reply wasn't clear, I think I've added to the confusion 😆 

You're totally right that the function isn't clear that it's only matching the first solution, so :+1: for making that clearer.

The issue I wanted to highlight is that there is a recent trend to rename existing conventions to peoples personal preferences.

This is actually a perfect example as the concept is documented as a "[solution](https://github.com/pelias/parser#solvers)", the docs say "Each parse can contain multiple solutions".

From the thread I can see that David prefers the term 'parse' and Julian prefers the term 'match'.

The problem with either of these is that someone will inevitably come along at a later date and say that they find the term 'parse' or 'match' inconsistent with the documentation and attempt to rename one or the other again, and they'd be right.

**Comment by missinglink** [comment]
The reason we tend to prefer to only test the first solution is so that the tests are less brittle when changes are made.

The 'Wrigley Field' test case now ensures that a solution of `locality: Field` is always returned, this may confuse a developer at a later date who isn't sure if that's expected behaviour or not and so they may be too afraid to change it.

I think this is the first time we've wanted to test that two solutions are returned for a parse, so it's new territory.
If our intention is to ensure that the `place` and `street` solutions are correct but we don't care to cover the `locality` solution then neither of the existing `first` nor `all` assertion methods are able to adequately cover this case.

**Comment by blackmad** [comment]
Hey Peter,

Thanks for the detailed followups

re: naming conventions, I don't want to confuse the conventions. While I was writing this I wondered if I should be using the term "solution" rather than "parser" - I'm happy to change it. I don't want to introduce new vocabulary at all.

re: wrigley field - good point that the test is now somewhat testing for buggy behavior. Would you like me to add a third matcher that's more along the lines of a some/contains matcher?

**Comment by missinglink** [comment]
Yeah I think so, I don't like the idea of reinforcing undesirable behaviour in tests if we can avoid it.

Although it's is not urgent and need not block the semantic changes you proposed to make the assertion function call clearer as to which solutions it's considering.

**Comment by blackmad** [comment]
updated to use "solution" vocab, and also to only match the first N expected values

**Pull request closed without merging**
