### PR TITLE
Add personal title classifier (fra addresses)

### PR DESCRIPTION
**Pull request by Joxit**
## Supports for

- `Boulevard` `Charles De Gaulle` (Street + Person)
- `Rue` `Saint` `Lazarre` (Street + Title + Given Name)
- `Boulevard` `du` `Général` `Charles De Gaulle` (Street + Stop Word + Title + Person)
- `Rue` `Jean` `Nicot` (Street + Given Name + Surname)

## :warning: for Street + Given Name + Surname

- I added `AlphaClassification` as alternative to Given Name for matching `Avenue Aristide Briand` because Aristide is not in Given Name dictionary. Should I add the missing french names in the dictionary ?
- Confidence is 0.92 because for `Allée Victor Hugo`. When `Hugo` is classified as locality its score is 0.91. 

```
================================================================
SOLUTIONS (3ms)
----------------------------------------------------------------
(0.92) ➜ [ { street: 'Allée Victor Hugo' } ]

(0.91) ➜ [ { street: 'Allée Victor' }, { locality: 'Hugo' } ]

(0.40) ➜ [ { locality: 'Victor' } ]
```

### CODE REVIEW

**Comment by missinglink** [comment]
Nice catch, I must have missed this one...

```
➜  parser git:(version) find . | grep people.txt
./resources/libpostal/dictionaries/all/people.txt
./resources/libpostal/dictionaries/fr/people.txt
```

Looks good to me.

I'm not sure what to do about the dictionaries, it's clear we will need to edit them at some point but it seems nice to leave the `libpostal` ones unedited so we can update them at a later date if that project gets active again.

Maybe we can just create a new `resource` which mirrors the directory format? I'd also like to be able to remove tokens from what `libpostal` specifies, with something like a `!foo` syntax.

Let's discuss that in another PR?

**Comment by missinglink** [comment]
Also just an FYI:

I just merged some changes today, and as part of that, I am trying to change the way we specify the `scheme(s)` a bit.

I'm trying something a bit different... which works because the schemes are evaluated from top-to-bottom, so if you managed to classify a street as something like:

```
  {
    // Main Street
    confidence: 0.82,
    Class: StreetClassification,
    scheme: [
      {
        is: ['AlphaClassification'],
        not: ['StreetClassification', 'IntersectionClassification']
      },
      {
        is: ['StreetSuffixClassification'],
        not: ['StreetClassification', 'IntersectionClassification']
      }
    ]
  },
```

.. then it's possible to add a directional later in the file with another scheme such as:

```
  {
    // West Main Street
    confidence: 0.84,
    Class: StreetClassification,
    scheme: [
      {
        is: ['DirectionalClassification'],
        not: ['StreetClassification', 'IntersectionClassification']
      },
      {
        is: ['StreetClassification'],
        not: ['DirectionalClassification']
      }
    ]
  },
```

This is cool because it means it's more flexible for streets with multiple words.
So the idea I had is that we can classify the street and then 'grow' the classification until it covers adjacent tokens.

This coupled with the fact that the street confidence values are lower than the admin ones means that we should be able to 'greedy parse' street tokens but still score solutions in a way that doesn't overly favour street names over admin names.

**Comment by missinglink** [comment]
Also, the street confidence scores are all just made up :)
So things like `0.84` are just a number I plucked out of thin air which seemed to work, so I'm not against changing any of them.

Let's keep building up the functional tests, they are super useful when changing schema files because it's possible to see what effect a change has on other queries.

**Comment by missinglink** [comment]
I think it's best to do what you're doing for the tests, where you pass the `true` flag to only test the top result, otherwise the tests change too often and it's annoying to maintain them :+1:

**Comment by Joxit** [comment]
I'm ok with leaving `libpostal` unedited. 

Something like `resources/pelias/dictionaries/given_names.txt` which contains
```
Aristide
!foo
...
```
This could be a very good idea :+1:
And then we will be able to do the same with a `resources/custom/dictionaries/..` for user specific dictionaries

---

You gave me a idea:
:memo: Create a `CompositeClassifier` : `GivenNameClassification` + `SurnameClassification` => `PersonClassification`
This will cover more people who are not in `people.txt` file.

**Pull request merged**
