### PR TITLE
update person schema to allow middle name, add brazil testcase

### PR DESCRIPTION
**Pull request by missinglink**
Hi @blackmad

I had another look at this after our call (and after eating dinner) and managed to get it working with the following changes.

@Joxit does this look ok to you?  it didn't break any tests.

closes https://github.com/pelias/parser/issues/98

### CODE REVIEW

**Comment by missinglink** [comment]
Maybe I should add a new scheme rather than editing the existing one?

**Comment by missinglink** [comment]
Another way of doing it is to revert this and instead add:

```javascript
  {
    // Boulevard du Général Charles De Gaulle
    confidence: 0.81,
    Class: StreetClassification,
    scheme: [
      {
        is: ['StreetPrefixClassification'],
        not: ['StreetClassification', 'IntersectionClassification']
      },
      {
        is: ['GivenNameClassification', 'SurnameClassification'],
        not: ['StreetClassification', 'IntersectionClassification']
      },
      {
        is: ['GivenNameClassification', 'SurnameClassification'],
        not: ['StreetClassification', 'IntersectionClassification']
      },
      {
        is: ['GivenNameClassification', 'SurnameClassification'],
        not: ['StreetClassification', 'StreetPrefixClassification']
      }
    ]
  },
```

**Comment by Joxit** [comment]
Hi @missinglink, `Raul Leite Magalhães` is a person so you should update [`classifier/scheme/person.js`](https://github.com/pelias/parser/blob/dac59f4c999e82bd5747fa0f03aad42bb3ad360a/classifier/scheme/person.js) instead of [`classifier/scheme/street.js`](https://github.com/pelias/parser/blob/dac59f4c999e82bd5747fa0f03aad42bb3ad360a/classifier/scheme/street.js).

Add the case 1 GivenName with 2 Surnames. This will classify `Raul Leite Magalhães` as a person and then 
https://github.com/pelias/parser/blob/dac59f4c999e82bd5747fa0f03aad42bb3ad360a/classifier/scheme/street.js#L20-L33
will do the job

**Comment by Joxit** [comment]
Updating `person.js` will also provide support for inputs like `Saint Raul Leite Magalhães`

**Comment by missinglink** [comment]
Nice, I totally forgot how all this works already :P

**Comment by Joxit** [comment]
Oh, another solution is to add just after the case `GivenNameClassification`

```js
  {
    // Leite Magalhães
    confidence: 0.25,
    Class: SurnameClassification,
    scheme: [
      {
        is: ['SurnameClassification'],
        not: ['StreetClassification', 'IntersectionClassification']
      },
      {
        is: ['SurnameClassification'],
        not: ['StreetClassification', 'StreetPrefixClassification', 'StopWordClassification']
      }
    ]
  }
```

This will reclassify `Leite Magalhães` as Surname and voilà :smile:

**Comment by missinglink** [comment]
Fixed via rebase.

**Pull request merged**
