### PR TITLE
Add person composite classifier

### PR DESCRIPTION
**Pull request by Joxit**
## Supports for

- Compound given names (e.g [`Jean Baptiste Clément`](https://pelias.github.io/compare/#/v1/autocomplete%3Ftext=Rue%20Jean%20Baptiste%20Cl%C3%A9ment))
- Given Name + Surname (e.g Georges Bizet)
- Given Name + stop word + Surname (e.g Maria de Carvalho)

### CODE REVIEW

**Comment by missinglink** [comment]
Heya, would you like to merge these commits in this PR?
https://github.com/pelias/parser/compare/locality_fra?expand=1

That would enable French language locality names.

**Comment by missinglink** [comment]
I'll merge that PR anyway and you can add more files for the French language if you like?

**Comment by missinglink** [comment]
Please rebase `master` and `Dunkerque` / `Marseille` should now parse correctly.

**Comment by Joxit** [comment]
Ok :+1: and what about #9 for WOF dictionaries ?

**Comment by missinglink** [comment]
It feels so nice to have control over how things get parsed ;)

**Pull request merged**
