### PR TITLE
venue classification work

### PR DESCRIPTION
**Pull request by blackmad**
- add middle initial classification for people
- add [person] [venue] for venue

In 1000 random queries, this only affects 5. three are minor scoring changes, two are at positions above 0.

### CODE REVIEW

**Comment by blackmad** [comment]
bump

**Review by Joxit — APPROVED** [review]
LGTM, can you rebase the branch ?

**Comment by Joxit** [comment]
Sync again :sweat_smile:

**Comment by blackmad** [comment]
fixed merge conflict

**Pull request merged**
